base_url: "https://sampaijadi.github.io/projek/"
footer_text: '&copy; 2026'
hero_subtitle: Tanam Tinggal Tuai
hero_subtitle_weight: '400'
hero_title: Sistem Siraman Automatik
hero_title_weight: '700'
site_description: Panduan sistem siraman automatik
