footer_text: '&copy; 2026'
hero_subtitle: Tanam Tinggal Tuai
hero_title: Sistem Siraman Automatik
site_description: A minimalist CMS powered by Python and Pico.css. Perfect for hosting
  on GitHub Pages.
